spring.application.name=reseking
spring.mvc.servlet.path=/api

# Server
server.port=${SERVER_PORT:8080}

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

# JWT
security.jwt.secret=${SECURITY_JWT_SECRET}
security.jwt.expiration-minutes=${SECURITY_JWT_EXPIRATION_MINUTES:120}


# RabbitMQ
spring.rabbitmq.host=${SPRING_RABBITMQ_HOST}
spring.rabbitmq.port=${SPRING_RABBITMQ_PORT}
spring.rabbitmq.username=${SPRING_RABBITMQ_USERNAME}
spring.rabbitmq.password=${SPRING_RABBITMQ_PASSWORD}
